<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LicenseFlow.SDK</AssemblyName>
    <RootNamespace>LicenseFlow.SDK</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.35.0" />
  </ItemGroup>
</Project>
