<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LicenseFlow.SDK</AssemblyName>
    <RootNamespace>LicenseFlow.SDK</RootNamespace>
    <Version>2.1.0</Version>
    <Authors>LicenseFlow</Authors>
    <Company>LicenseFlow</Company>
    <Description>Official .NET SDK for LicenseFlow — Licensing, activation, entitlements, floating licenses, and distribution.</Description>
    <PackageProjectUrl>https://licenseflow.dev</PackageProjectUrl>
    <RepositoryUrl>https://github.com/licenseflow/dotnet-sdk</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>license;licensing;activation;entitlements;floating-license;software-distribution</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.35.0" />
    <PackageReference Include="NSec.Cryptography" Version="24.4.0" />
  </ItemGroup>
</Project>
